# Build in the node.js image
FROM node:latest as build-stage

# Create a folder to add the code to
WORKDIR /app

# Read brand from args and set in environment
ARG BRAND
ENV BRAND $BRAND

# Copy in package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the code into the container
COPY . .

# Set the server to run when executing the docker image
CMD node server.js